import { Book } from './book';

export const BOOKS: [string, Book][] = [
  ['Genesis', Book.Genesis],
  ['Exodus', Book.Exodus],
  ['Leviticus', Book.Leviticus],
  ['Numbers', Book.Numbers],
  ['Deuteronomy', Book.Deuteronomy],
  ['Joshua', Book.Joshua],
  ['Judges', Book.Judges],
  ['Ruth', Book.Ruth],
  ['First Samuel', Book.FirstSamuel],
  ['Second Samuel', Book.SecondSamuel],
  ['First Kings', Book.FirstKings],
  ['Second Kings', Book.SecondKings],
  ['First Chronicles', Book.FirstChronicles],
  ['Second Chronicles', Book.SecondChronicles],
  ['1 Samuel', Book.FirstSamuel],
  ['2 Samuel', Book.SecondSamuel],
  ['1 Kings', Book.FirstKings],
  ['2 Kings', Book.SecondKings],
  ['1 Chronicles', Book.FirstChronicles],
  ['2 Chronicles', Book.SecondChronicles],
  ['Ezra', Book.Ezra],
  ['Nehemiah', Book.Nehemiah],
  ['Esther', Book.Esther],
  ['Job', Book.Job],
  ['Psalms', Book.Psalms],
  ['Proverbs', Book.Proverbs],
  ['Ecclesiastes', Book.Ecclesiastes],
  ['Song of Solomon', Book.SongOfSolomon],
  ['Song of Songs', Book.SongOfSolomon],
  ['Cantic', Book.SongOfSolomon],
  ['Isaiah', Book.Isaiah],
  ['Jeremiah', Book.Jeremiah],
  ['Lamentations', Book.Lamentations],
  ['Lam', Book.Lamentations],
  ['Ezekiel', Book.Ezekiel],
  ['Daniel', Book.Daniel],
  ['Hosea', Book.Hosea],
  ['Joel', Book.Joel],
  ['Amos', Book.Amos],
  ['Obadiah', Book.Obadiah],
  ['Jonah', Book.Jonah],
  ['Micah', Book.Micah],
  ['Nahum', Book.Nahum],
  ['Habakkuk', Book.Habakkuk],
  ['Zephaniah', Book.Zephaniah],
  ['Haggai', Book.Haggai],
  ['Zechariah', Book.Zechariah],
  ['Malachi', Book.Malachi],
  ['Matthew', Book.Matthew],
  ['Mark', Book.Mark],
  ['Luke', Book.Luke],
  ['John', Book.John],
  ['Acts', Book.Acts],
  ['Romans', Book.Romans],
  ['1 Corinthians', Book.FirstCorinthians],
  ['First Corinthians', Book.FirstCorinthians],
  ['2 Corinthians', Book.SecondCorinthians],
  ['Second Corinthians', Book.SecondCorinthians],
  ['Galatians', Book.Galatians],
  ['Ephesians', Book.Ephesians],
  ['Philippians', Book.Ephesians],
  ['Phil', Book.Philippians],
  ['Colossians', Book.Colossians],
  ['1 Thessalonians', Book.FirstThessalonians],
  ['First Thessalonians', Book.FirstThessalonians],
  ['2 Thessalonians', Book.SecondThessalonians],
  ['Second Thessalonians', Book.SecondThessalonians],
  ['1 Timothy', Book.FirstTimothy],
  ['First Timothy', Book.FirstTimothy],
  ['1 Tim', Book.FirstTimothy],
  ['2 Timothy', Book.SecondTimothy],
  ['Second Timothy', Book.SecondTimothy],
  ['2 Tim', Book.SecondTimothy],
  ['Titus', Book.Titus],
  ['Philemon', Book.Philemon],
  ['Phlm', Book.Philemon],
  ['Hebrews', Book.Hebrews],
  ['James', Book.James],
  ['1 Peter', Book.FirstPeter],
  ['First Peter', Book.FirstPeter],
  ['2 Peter', Book.SecondPeter],
  ['Second Peter', Book.SecondPeter],
  ['1 John', Book.FirstJohn],
  ['2 John', Book.SecondJohn],
  ['3 John', Book.ThirdJohn],
  ['First John', Book.FirstJohn],
  ['Second John', Book.SecondJohn],
  ['Third John', Book.ThirdJohn],
  ['Jude', Book.Jude],
  ['Revelation', Book.Revelation],
  ['Apocalypse', Book.Revelation],
];
