/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LiturgicalDocument, } from "@venite/ldf";
export namespace Components {
    interface LdfEditor {
        "doc": LiturgicalDocument | string;
    }
}
declare global {
    interface HTMLLdfEditorElement extends Components.LdfEditor, HTMLStencilElement {
    }
    var HTMLLdfEditorElement: {
        prototype: HTMLLdfEditorElement;
        new (): HTMLLdfEditorElement;
    };
    interface HTMLElementTagNameMap {
        "ldf-editor": HTMLLdfEditorElement;
    }
}
declare namespace LocalJSX {
    interface LdfEditor {
        "doc"?: LiturgicalDocument | string;
    }
    interface IntrinsicElements {
        "ldf-editor": LdfEditor;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ldf-editor": LocalJSX.LdfEditor & JSXBase.HTMLAttributes<HTMLLdfEditorElement>;
        }
    }
}
