export const WEB_FONTS = [
  "Arial",
  "Baskerville",
  "Bodoni MT",
  "Calibri",
  "Calisto MT",
  "Cambria",
  "Candara",
  "Century Gothic",
  "Consolas",
  "Copperplate Gothic",
  "Courier New",
  "Dejavu Sans",
  "Didot",
  "Franklin Gothic",
  "Garamond",
  "Georgia",
  "Goudy Old Style",
  "Helvetica",
  "Impact",
  "Lucida Bright",
  "Lucida Sans",
  "Microsoft Sans Serif",
  "Optima",
  "Palatino",
  "Perpetua",
  "Rockwell",
  "Segoe UI",
  "Tahoma",
  "Trebuchet MS",
  "Verdana",
];
