const rite1 = [
  {
    metadata: {
      omit_response: true,
      rollup: false,
      omit_label: false,
      response: null,
    },
    language: "en",
    type: "text",
    slug: "proper_preface",
    lastRevision: 3,
    version_label: "Easter",
    citation: null,
    style: "text",
    label: null,
    source: {
      citation: "",
      source: "",
      api: "",
    },
    version: "rite_i",
    category: ["Easter", "Proper Preface"],
    value: [
      "But chiefly are we bound to praise thee for the glorious resurrection of thy Son Jesus Christ our Lord; for he is the very Paschal Lamb, who was sacrificed for us, and hath taken away the sin of the world; who by his death hath destroyed death, and by his rising to life again hath won for us everlasting life.",
    ],
    hidden: false,
  },
  {
    version_label: "Trinity Sunday",
    label: null,
    style: "text",
    metadata: {
      omit_response: true,
      response: null,
    },
    version: "rite_i",
    category: ["Trinity", "Proper Preface"],
    language: "en",
    citation: null,
    hidden: false,
    type: "text",
    slug: "proper_preface",
    value: [
      "For with thy co-eternal Son and Holy Spirit, thou art one God, one Lord, in Trinity of Persons and in Unity of Substance; and we celebrate the one and equal glory of thee, O Father, and of the Son, and of the Holy Spirit.",
    ],
  },
  {
    hidden: false,
    category: ["Advent", "Proper Preface"],
    value: [
      " Because thou didst send thy beloved Son to redeem us from sin and death, and to make us heirs in him of everlasting life; that when he shall come again in power and great triumph to judge the world, we may without shame or fear rejoice to behold his appearing.",
    ],
    language: "en",
    citation: null,
    version_label: "Advent",
    style: "text",
    slug: "proper_preface",
    label: null,
    version: "rite_i",
    metadata: {
      omit_response: true,
      response: null,
    },
    type: "text",
  },
  {
    citation: null,
    label: null,
    category: ["Christmas", "Proper Preface"],
    metadata: {
      response: null,
      omit_response: true,
    },
    slug: "proper_preface",
    hidden: false,
    type: "text",
    version_label: "Incarnation",
    version: "rite_i",
    language: "en",
    style: "text",
    value: [
      "Because thou didst give Jesus Christ, thine only Son, to be born for us; who, by the mighty power of the Holy Ghost, was made very Man of the substance of the Virgin Mary his mother; that we might be delivered from the bondage of sin, and receive power to become thy children.",
    ],
  },
  {
    hidden: false,
    language: "en",
    version_label: "Epiphany",
    version: "rite_i",
    slug: "proper_preface",
    label: null,
    citation: null,
    type: "text",
    value: [
      "Because in the mystery of the Word made flesh, thou hast caused a new light to shine in our hearts, to give the knowledge of thy glory in the face of thy Son Jesus Christ our Lord.",
    ],
    metadata: {
      response: null,
      omit_response: true,
    },
    category: ["Epiphany", "Proper Preface"],
    style: "text",
  },
  {
    language: "en",
    version: "rite_i",
    metadata: {
      omit_response: true,
      response: null,
    },
    label: null,
    value: [
      "  Through Jesus Christ our Lord; who rose victorious from the dead, and doth comfort us with the blessed hope of everlasting life; for to thy faithful people, O Lord, life is changed, not ended; and when our mortal body doth lie in death, there is prepared for us a dwelling place eternal in the heavens.",
    ],
    hidden: false,
    type: "text",
    style: "text",
    slug: "proper_preface",
    citation: null,
    version_label: "Commemoration of the Dead",
    category: ["Funeral", "Proper Preface"],
  },
  {
    label: null,
    style: "text",
    citation: null,
    language: "en",
    metadata: {
      response: null,
      omit_response: true,
    },
    slug: "proper_preface",
    type: "text",
    category: ["Lent", "Proper Preface"],
    version: "rite_i",
    value: [
      "Who dost bid thy faithful people cleanse their hearts, and prepare with joy for the Paschal feast; that, fervent in prayer and in works of mercy, and renewed by thy Word and Sacraments, they may come to the fullness of grace which thou hast prepared for those who love thee.",
    ],
    hidden: false,
    version_label: "Lent",
  },
  {
    type: "text",
    label: null,
    version_label: "A Saint",
    style: "text",
    citation: null,
    category: ["Saints", "Proper Preface"],
    metadata: {
      response: null,
      omit_response: true,
    },
    version: "rite_i",
    language: "en",
    hidden: false,
    slug: "proper_preface",
    value: [
      "Because thou art greatly glorified in the assembly of thy saints. All thy creatures praise thee, and thy faithful servants bless thee, confessing before the rulers of this world the great Name of thine only Son.",
    ],
  },
  {
    slug: "proper_preface",
    label: null,
    version_label: "All Saints’",
    type: "text",
    version: "rite_i",
    category: ["Saints", "Proper Preface"],
    value: [
      "Who, in the multitude of thy saints, hast compassed us about with so great a cloud of witnesses, that we, rejoicing in their fellowship, may run with patience the race that is set before us; and, together with them, may receive the crown of glory that fadeth not away.",
    ],
    citation: null,
    hidden: false,
    language: "en",
    metadata: {
      response: null,
      omit_response: true,
    },
    style: "text",
  },
  {
    label: null,
    style: "text",
    citation: null,
    category: ["Saints", "Proper Preface"],
    hidden: false,
    version: "rite_i",
    metadata: {
      response: null,
      omit_response: true,
    },
    slug: "proper_preface",
    language: "en",
    version_label: "A Saint",
    value: [
      "  Who in the obedience of thy saints hast given us an example of righteousness, and in their eternal joy a glorious pledge of the hope of our calling.",
    ],
    type: "text",
  },
  {
    category: ["Baptism", "Proper Preface"],
    type: "text",
    value: [
      "Because in Jesus Christ our Lord thou hast received us as thy sons and daughters, made us citizens of thy kingdom, and given us the Holy Spirit to guide us into all truth.",
    ],
    version_label: "Baptism",
    slug: "proper_preface",
    hidden: false,
    style: "text",
    label: null,
    version: "rite_i",
    citation: null,
    language: "en",
    metadata: {
      response: null,
      omit_response: true,
    },
  },
  {
    version_label: "Lent",
    type: "text",
    slug: "proper_preface",
    language: "en",
    version: "rite_i",
    category: ["Lent", "Proper Preface"],
    hidden: false,
    style: "text",
    metadata: {
      response: null,
      omit_response: true,
    },
    value: [
      "Through Jesus Christ our Lord; who was in every way tempted as we are, yet did not sin; by whose grace we are able to triumph over every evil, and to live no longer unto ourselves, but unto him who died for us and rose again.",
    ],
    citation: null,
    label: null,
  },
  {
    language: "en",
    value: [
      "  Because in the love of wife and husband, thou hast given us an image of the heavenly Jerusalem, adorned as a bride for her bridegroom, thy Son Jesus Christ our Lord; who loveth her and gave himself for her, that he might make the whole creation new.",
    ],
    hidden: false,
    version_label: "Marriage",
    category: ["Marriage", "Proper Preface"],
    label: null,
    version: "rite_i",
    style: "text",
    metadata: {
      omit_response: true,
      response: null,
    },
    slug: "proper_preface",
    citation: null,
    type: "text",
  },
  {
    version: "rite_i",
    version_label: "Pentecost",
    style: "text",
    language: "en",
    slug: "proper_preface",
    value: [
      "Through Jesus Christ our Lord; according to whose true promise the Holy Ghost came down [on this day] from heaven, lighting upon the disciples, to teach them and to lead them into all truth; uniting peoples of many tongues in the confession of one faith, and giving to thy Church the power to serve thee as a royal priesthood, and to preach the Gospel to all nations.",
    ],
    category: ["Pentecost", "Proper Preface"],
    citation: null,
    label: null,
    metadata: {
      omit_response: true,
      response: null,
    },
    hidden: false,
    type: "text",
  },
  {
    value: [
      "Through Jesus Christ our Lord; who for our sins was lifted high upon the cross, that he might draw the whole world to himself; who by his suffering and death became the author of eternal salvation for all who put their trust in him.",
    ],
    hidden: false,
    slug: "proper_preface",
    language: "en",
    label: null,
    version: "rite_i",
    metadata: {
      response: null,
      omit_response: true,
    },
    version_label: "Holy Week",
    style: "text",
    type: "text",
    category: ["HolyWeek", "Proper Preface"],
    citation: null,
  },
  {
    hidden: false,
    metadata: {
      response: null,
      omit_response: true,
    },
    version_label: "Ascension",
    version: "rite_i",
    style: "text",
    label: null,
    citation: null,
    type: "text",
    language: "en",
    category: ["Ascension", "Proper Preface"],
    slug: "proper_preface",
    value: [
      "Through thy dearly beloved Son Jesus Christ our Lord; who after his glorious resurrection manifestly appeared to his disciples; and in their sight ascended into heaven, to prepare a place for us; that where he is, there we might also be, and reign with him in glory.",
    ],
  },
  {
    version: "rite_i",
    slug: "proper_preface",
    category: ["OrdinaryTime", "Proper Preface"],
    style: "text",
    label: null,
    language: "en",
    metadata: {
      response: null,
      omit_response: true,
    },
    hidden: false,
    version_label: "Of God the Holy Spirit",
    type: "text",
    citation: null,
    value: [
      " Who by water and the Holy Spirit hast made us a new people in Jesus Christ our Lord, to show forth thy glory in all the world.",
    ],
  },
  {
    hidden: false,
    version: "rite_i",
    version_label: "A Saint",
    style: "text",
    type: "text",
    value: [
      "For the wonderful grace and virtue declared in all thy saints, who have been chosen vessels of thy grace, and the lights of the world in their generations.",
    ],
    category: ["Saints", "Proper Preface"],
    slug: "proper_preface",
    language: "en",
    citation: null,
    metadata: {
      response: null,
      omit_response: true,
    },
    label: null,
  },
  {
    language: "en",
    version_label: "Of God the Son",
    type: "text",
    value: [
      "  Through Jesus Christ our Lord; who on the first day of the week overcame death and the grave, and by his glorious resurrection opened to us the way of everlasting life.",
    ],
    hidden: false,
    version: "rite_i",
    category: ["OrdinaryTime", "Proper Preface"],
    slug: "proper_preface",
    citation: null,
    style: "text",
    label: null,
    metadata: {
      omit_response: true,
      response: null,
    },
  },
  {
    value: [
      " Creator of the light and source of life, who hast made us in thine image, and called us to new life in Jesus Christ our Lord.",
    ],
    type: "text",
    metadata: {
      omit_response: true,
      response: null,
    },
    version: "rite_i",
    slug: "proper_preface",
    style: "text",
    version_label: "Of God the Father",
    citation: null,
    hidden: false,
    label: null,
    category: ["OrdinaryTime", "Proper Preface"],
    language: "en",
  },
];

const rite2 = [
  {
    category: ["Trinity", "Proper Preface"],
    value: [
      " For with your co-eternal Son and Holy Spirit, you are one God, one Lord, in Trinity of Persons and in Unity of Being; and we celebrate the one and equal glory of you, O Father, and of the Son, and of the Holy Spirit.",
    ],
    version_label: "Trinity Sunday",
    version: "bcp1979",
    slug: "proper_preface",
    label: null,
    style: "text",
    citation: null,
    type: "text",
    metadata: {
      omit_response: true,
      response: null,
    },
    hidden: false,
    language: "en",
  },
  {
    label: null,
    style: "text",
    citation: null,
    hidden: false,
    type: "text",
    version: "bcp1979",
    metadata: {
      omit_response: true,
      response: null,
    },
    category: ["Epiphany", "Proper Preface"],
    slug: "proper_preface",
    value: [
      "Because in the mystery of the Word made flesh, you have caused a new light to shine in our hearts, to give the knowledge of your glory in the face of your son Jesus Christ our Lord.",
    ],
    language: "en",
    version_label: "Epiphany",
  },
  {
    value: [
      "For by water and the Holy Spirit you have made us a new people in Jesus Christ our Lord, to show forth your glory in all the world.",
    ],
    label: null,
    language: "en",
    style: "text",
    citation: null,
    slug: "proper_preface",
    hidden: false,
    version: "bcp1979",
    metadata: {
      omit_response: true,
      response: null,
    },
    type: "text",
    category: ["OrdinaryTime", "Proper Preface"],
    version_label: "Of God the Holy Spirit",
  },
  {
    version_label: "Pentecost",
    language: "en",
    style: "text",
    type: "text",
    value: [
      "Through Jesus Christ our Lord. In fulfillment of his true promise, the Holy Spirit came down [on this day] from heaven, lighting upon the disciples, to teach them and to lead them into all truth; uniting peoples of many tongues in the confession of one faith, and giving to your Church the power to serve you as a royal priesthood, and to preach the Gospel to all nations.",
    ],
    hidden: false,
    citation: null,
    label: null,
    version: "bcp1979",
    category: ["Pentecost", "Proper Preface"],
    metadata: {
      omit_response: true,
      response: null,
    },
    slug: "proper_preface",
  },
  {
    hidden: false,
    style: "text",
    category: ["Lent", "Proper Preface"],
    type: "text",
    label: null,
    language: "en",
    value: [
      "You bid your faithful people cleanse their hearts, and prepare with joy for the Paschal feast; that, fervent in prayer and in works of mercy, and renewed by your Word and Sacraments, they may come to the fullness of grace which you have prepared for those who love you.",
    ],
    citation: null,
    slug: "proper_preface",
    metadata: {
      omit_response: true,
      response: null,
    },
    version: "bcp1979",
    version_label: "Lent",
  },
  {
    style: "text",
    hidden: false,
    label: null,
    metadata: {
      response: null,
      omit_response: true,
    },
    slug: "proper_preface",
    category: ["Lent", "Proper Preface"],
    language: "en",
    version_label: "Lent",
    version: "bcp1979",
    type: "text",
    citation: null,
    value: [
      "Through Jesus Christ our Lord; who was tempted in every way as we are, yet did not sin. By his grace we are able to triumph over every evil, and to live no longer for ourselves alone, but for him who died for us and rose again.",
    ],
  },
  {
    slug: "proper_preface",
    type: "text",
    value: [
      "Through Jesus Christ our Lord; who rose victorious from the dead, and comforts us with the blessed hope of everlasting life. For to your faithful people, O Lord, life is changed, not ended; and when our mortal body lies in death, there is prepared for us a dwelling place eternal in the heavens.",
    ],
    category: ["Funeral", "Proper Preface"],
    citation: null,
    language: "en",
    label: null,
    metadata: {
      response: null,
      omit_response: true,
    },
    version: "bcp1979",
    version_label: "Commemoration of the Dead",
    hidden: false,
    style: "text",
  },
  {
    value: [
      " Because in the love of wife and husband, you have given us an image of the heavenly Jerusalem, adorned as a bride for her bridegroom, your Son Jesus Christ our Lord; who loves her and gave himself for her, that he might make the whole creation new.",
    ],
    style: "text",
    language: "en",
    hidden: false,
    version_label: "Marriage",
    metadata: {
      response: null,
      omit_response: true,
    },
    version: "bcp1979",
    citation: null,
    label: null,
    type: "text",
    slug: "proper_preface",
    category: ["Marriage", "Proper Preface"],
  },
  {
    slug: "proper_preface",
    language: "en",
    type: "text",
    citation: null,
    version: "bcp1979",
    label: null,
    category: ["Ascension", "Proper Preface"],
    version_label: "Ascension",
    value: [
      "Through your dearly beloved Son Jesus Christ our Lord. After his glorious resurrection he openly appeared to his disciples, and in their sight ascended into heaven, to prepare a place for us; that where he is, there we might also be, and reign with him in glory.",
    ],
    hidden: false,
    metadata: {
      omit_response: true,
      response: null,
    },
    style: "text",
  },
  {
    value: [
      "Because you sent your beloved Son to redeem us from sin and death, and to make us heirs in him of everlasting life; that when he shall come again in power and great triumph to judge the world, we may without shame or fear rejoice to behold his appearing.",
    ],
    slug: "proper_preface",
    category: ["Advent", "Proper Preface"],
    version: "bcp1979",
    citation: null,
    language: "en",
    metadata: {
      response: null,
      omit_response: true,
    },
    style: "text",
    label: null,
    version_label: "Advent",
    hidden: false,
    type: "text",
  },
  {
    version_label: "A Saint",
    citation: null,
    hidden: false,
    label: null,
    metadata: {
      omit_response: true,
      response: null,
    },
    version: "bcp1979",
    category: ["Saints", "Proper Preface"],
    style: "text",
    slug: "proper_preface",
    type: "text",
    value: [
      "For the wonderful grace and virtue declared in all your saints, who have been the chosen vessels of your grace, and the lights of the world in their generations.",
    ],
    language: "en",
  },
  {
    category: ["Baptism", "Proper Preface"],
    label: null,
    value: [
      "Because in Jesus Christ our Lord you have received us as your sons and daughters, made us citizens of your kingdom, and given us the Holy Spirit to guide us into all truth.",
    ],
    language: "en",
    hidden: false,
    metadata: {
      omit_response: true,
      response: null,
    },
    citation: null,
    version: "bcp1979",
    slug: "proper_preface",
    version_label: "Baptism",
    type: "text",
    style: "text",
  },
  {
    hidden: false,
    type: "text",
    version: "bcp1979",
    language: "en",
    citation: null,
    style: "text",
    category: ["Easter", "Proper Preface"],
    label: null,
    metadata: {
      response: null,
      omit_response: true,
    },
    slug: "proper_preface",
    value: [
      "But chiefly are we bound to praise you for the glorious resurrection of your Son Jesus Christ our Lord; for he is the true Paschal Lamb, who was sacrificed for us, and has taken away the sin of the world. By his death he has destroyed death, and by his rising to life again he has won for us everlasting life.",
    ],
    version_label: null,
  },
  {
    hidden: false,
    metadata: {
      response: null,
      omit_response: true,
    },
    type: "text",
    version_label: "A Saint",
    version: "bcp1979",
    citation: null,
    category: ["Saints", "Proper Preface"],
    label: null,
    slug: "proper_preface",
    style: "text",
    language: "en",
    value: [
      "Because in the obedience of your saints you have given us an example of righteousness, and in their eternal joy a glorious pledge of the hope of our calling.",
    ],
  },
  {
    metadata: {
      response: null,
      omit_response: true,
    },
    language: "en",
    version: "bcp1979",
    slug: "proper_preface",
    value: [
      "Through Jesus Christ our Lord; who on the first day of the week overcame death and the grave, and by his glorious resurrection opened to us the way of everlasting life.",
    ],
    citation: null,
    category: ["OrdinaryTime", "Proper Preface"],
    hidden: false,
    version_label: "Of God the Son",
    label: null,
    type: "text",
    style: "text",
  },
  {
    version_label: "A Saint",
    slug: "proper_preface",
    type: "text",
    style: "text",
    label: null,
    version: "bcp1979",
    language: "en",
    hidden: false,
    citation: null,
    metadata: {
      response: null,
      omit_response: true,
    },
    category: ["Saints", "Proper Preface"],
    value: [
      "Because you are greatly glorified in the assembly of your saints. All your creatures praise you, and your faithful servants bless you, confessing before the rulers of this world the great Name of your only Son.",
    ],
  },
  {
    version: "bcp1979",
    citation: null,
    value: [
      "For in the multitude of your saints you have surrounded us with a great cloud of witnesses, that we might rejoice in their fellowship, and run with endurance the race that is set before us; and, together with them, receive the crown of glory that never fades away.",
    ],
    hidden: false,
    slug: "proper_preface",
    category: ["Saints", "Proper Preface"],
    version_label: "All Saints’",
    metadata: {
      response: null,
      omit_response: true,
    },
    language: "en",
    type: "text",
    label: null,
    style: "text",
  },
  {
    label: null,
    hidden: false,
    value: [
      "For you are the source of light and life, you made us in your image, and called us to new life in Jesus Christ our Lord.",
    ],
    slug: "proper_preface",
    version: "bcp1979",
    style: "text",
    metadata: {
      response: null,
      omit_response: true,
    },
    citation: null,
    category: ["OrdinaryTime", "Proper Preface"],
    version_label: "Of God the Father",
    language: "en",
    type: "text",
  },
  {
    language: "en",
    citation: null,
    label: null,
    value: [
      "Because you gave Jesus Christ, your only Son, to be born for us; who, by the mighty power of the Holy Spirit, was made perfect Man of the flesh of the Virgin Mary his mother; so that we might be delivered from the bondage of sin, and receive power to become your children.",
    ],
    type: "text",
    metadata: {
      omit_response: true,
      response: null,
    },
    slug: "proper_preface",
    version_label: "Incarnation",
    style: "text",
    hidden: false,
    category: ["Christmas", "Proper Preface"],
    version: "bcp1979",
  },
  {
    version_label: "Holy Week",
    label: null,
    type: "text",
    style: "text",
    value: [
      "Through Jesus Christ our Lord. For our sins he was lifted high upon the cross, that he might draw the whole world to himself; and, by his suffering and death, he became the source of eternal salvation for all who put their trust in him.",
    ],
    slug: "proper_preface",
    citation: null,
    metadata: {
      response: null,
      omit_response: true,
    },
    hidden: false,
    category: ["HolyWeek", "Proper Preface"],
    version: "bcp1979",
    language: "en",
  },
];
